[build]
target = "./index.html"

[watch]
watch = [
    "../trading-charts/src",
    "../trading-charts/build.rs",
    "../trading-charts/Cargo.toml",
    "../trading-charts/bindings/src",
    "../trading-charts/bindings/build",
    "../trading-charts/bindings/package.json",
]

[serve]
address = "127.0.0.1"
port = 1420
open = true
