[workspace]
resolver = "3"
members = [
    "trading-charts-core",
    "trading-charts",
    "trading-charts-dioxus",
    "wasmbind-macro",
    "examples/leptos",
    "examples/dioxus",
]

default-members = ["trading-charts-core", "trading-charts", "trading-charts-dioxus", "wasmbind-macro"]

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Frédéric Meyer <frederic.meyer.77@gmail.com>"]
description = "Rust bindings of Lightweight Charts with Leptos and Dioxus adapters"
repository = "https://github.com/corebreaker/rs-trading-charts"
documentation = "https://docs.rs/trading-charts/"
readme = "README.md"
license = "MIT"
keywords = [
    "leptos",
    "dioxus",
]

categories = [
    "finance",
    "web-programming",
    "wasm",
]

# Pour exécuter ces commandes avec `cargo run-script`, il faut d'abord l'installer : `cargo install cargo-run-script`
[workspace.metadata.scripts]
fmt = "cargo +nightly fmt --all"
gc = "cargo sweep -r -t 10 ."

[workspace.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
dioxus = { version = "0.7", default-features = false }
dioxus-web = { version = "0.7", default-features = false }
emitix = { version = "1.1", features = ["leptos"] }
js-sys = "0.3"
leptos = { version = "0.8", features = ["csr"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlDivElement", "HtmlElement", "Node", "Window"] }
